### ISSUE TITLE
Feature: add image for social sharing

### ISSUE THREAD

**Issue by aristizabal95** [mjimenezleon13/clapHelp#10]
The app currently has no title, favicon, description and no OpenGraph metadata to display a preview on social media. This is necessary if we want the sharing functionality to yield good results. 

This will help: https://ahrefs.com/blog/open-graph-meta-tags/

**Comment by aristizabal95** [comment]
I'll work on this

**Comment by aristizabal95** [comment]
Just added the meta tags. We're only missing the image to display on social media. Would me nice if this image is the logo proposed by @mjimenezleon13 . I'll assign him the rest of this issue.
**STEPS**

1. Generate the image and store it inside the `/public` folder. (NOT IN `/public/images/`). This image should follow be **1200x630** and name it `og_image.jpg`
2. Change the meta tags:
```html
<meta property="og:image" content="">
<meta property="twitter:image" content="">
```
to
```html
<meta property="og:image" content="/og_image.jpg">
<meta property="twitter:image" content="/og_image.jpg">
```

**Comment by mjimenezleon13** [comment]
Changed it to:

<meta property="og:image" content="/og_image.jpeg">
<meta property="twitter:image" content="/og_image.jpeg">

(notice the file is .jpeg, not .jpg).
