### ISSUE TITLE
Feature: Implement a view to say thanks to anyone that shared their email

### ISSUE THREAD

**Issue by aristizabal95** [mjimenezleon13/clapHelp#12]
Currently, the UI flow stops at the contact form. This is not good UX, since the user will not have any feedback to know if the form was uploaded successfully, or how his data will be used. Making a simple response view saying _**Thank you, we will be sending you information in the upcoming days**_ would do the trick. Maybe even adding another share link would be good.

**Comment by aristizabal95** [comment]
Just saw the contact view already says thanks, so the next view should propably just assure the user that his email has been received

**Comment by mjimenezleon13** [comment]
¡Done!
Await for it in the next commit.
