### ISSUE TITLE
Fourth View: Where "XXXX" is, should say the option button user clicked.

### ISSUE THREAD

**Issue by mjimenezleon13** [mjimenezleon13/clapHelp#15]
To reach the email submission, the user clicks on different options. The text on the fourth view (the email submission view) should reffer to the option the user clicked, no just "XXXX"

**Comment by aristizabal95** [comment]
For now this has been temporarily removed, because the difficulty is higher than what it adds.

**Comment by mjimenezleon13** [comment]
The reason to do the follow up on this task, isn't really for the UX-UI within the platform, but so that we know what option the user clicked on for the follow up during the mail.
However, it's true, and I will create another issue which links the email address to the button chosen.

**Comment by aristizabal95** [comment]
We already know, the database stores this information

**Comment by aristizabal95** [comment]
![Screen Shot 2020-04-04 at 1 53 55 PM](https://user-images.githubusercontent.com/26156883/78459029-c10b0000-767b-11ea-9821-a12867256dc5.png)
Here's an example. The database knows which option the user chose
