### ISSUE TITLE
Link Domain to platform (launch).

### ISSUE THREAD

**Issue by mjimenezleon13** [mjimenezleon13/clapHelp#26]
Launch by linking domain to platform.

**Comment by aristizabal95** [comment]
Working on it

**Comment by aristizabal95** [comment]
We have to wait for the ssl certificate to be provided. It could take up to 24hrs

**Comment by aristizabal95** [comment]
SSL certificate has just been approved, and the domain is now working properly. This closes this issue and closes #32
