### ISSUE TITLE
Feature: add working share button

### ISSUE THREAD

**Issue by aristizabal95** [mjimenezleon13/clapHelp#9]
The current share button doesn't work. Replace it with a working share button.
This may help: https://sharethis.com/onboarding/

**Comment by mjimenezleon13** [comment]
I would suggest a different approach:
How about using the native share the browsers (in the smartphones) already have. 
And in case the user is doing it through a desktop, just adding it to the clipboard of the user and showing a pop-up saying: "Link copied successfully".

**Comment by mjimenezleon13** [comment]
I'm going to try to implement it.
Found this guide:
https://css-tricks.com/how-to-use-the-web-share-api/

**Comment by mjimenezleon13** [comment]
Ok, made the changes proposed in this link:
https://mobiforge.com/design-development/sharing-buttons-and-the-web-share-api
However, couldn't check if it actually worked due to the fact that it's meant to be supported by Chrome in desktop.

**Comment by aristizabal95** [comment]
PR #29 closes this issue
